### ISSUE TITLE
working with telegram keyboards

### ISSUE THREAD

**Issue by n0an** [ShaneQi/ZEGBot#2]
Hi. Does your bot framework handle telegram keyboards in some way now? I couldn't find any keyboard mentions in source code.

**Comment by ShaneQi** [comment]
I'm sorry, this framework doesn't include keyboard stuff. We have the plan to complete that part, just don't have the time yet.

**Comment by ShaneQi** [comment]
BTW, any PRs are welcome and will be greatly appreciated.

**Comment by ShaneQi** [comment]
@n0an Just in case you're still interested, I added support for `InlineKeyboardButton`, `InlineKeyboardMarkup` and `CallbackQuery`.
