### ISSUE TITLE
Deploy to Digital Ocean

### ISSUE THREAD

**Issue by hell4opt** [ShaneQi/ZEGBot#4]
How i can fix that?

root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/Methods.swift:256:18: error: use of unresolved identifier 'URLRequest'
                        var request = URLRequest(url: URL(string: urlPrefix + method)!)
                                      ^~~~~~~~~~
/root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/Methods.swift:263:15: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
                        let task = URLSession(configuration: .default).dataTask(with: request) { data, _, error in
                                   ^~~~~~~~~~
Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
public typealias URLSession = AnyObject
                 ^
/root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/ZEGBot.swift:18:25: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
        internal let session = URLSession(configuration: .default)
                               ^~~~~~~~~~
Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
public typealias URLSession = AnyObject
                 ^
/root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/Methods.swift:256:18: error: use of unresolved identifier 'URLRequest'
                        var request = URLRequest(url: URL(string: urlPrefix + method)!)
                                      ^~~~~~~~~~
/root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/Methods.swift:263:15: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
                        let task = URLSession(configuration: .default).dataTask(with: request) { data, _, error in
                                   ^~~~~~~~~~
Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
public typealias URLSession = AnyObject
                 ^
/root/VKPost_Bot/.build/checkouts/ZEGBot/Sources/ZEGBot.swift:18:25: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
        internal let session = URLSession(configuration: .default)
                               ^~~~~~~~~~
Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
public typealias URLSession = AnyObject

**Comment by ShaneQi** [comment]
It's the change of Swift 5.1.X that caused this error. I have updated the code accordingly, please make sure you are using the new version (4.2.2):

`.package(url: "https://github.com/shaneqi/ZEGBot.git", from: Version(4, 2, 2))`

**Comment by hell4opt** [comment]
thx!
