### ISSUE TITLE
sometimes the bot stops working

### ISSUE THREAD

**Issue by dimabiserov** [ShaneQi/ZEGBot#8]
Hello! I use DO as a server  with vapor 3 and your pod, and so completely chaotic and/or a long downtime (let's say a week), the bot stops responding. and i to go to DO and reboot it, do not know what could be the problem? maybe the web hook is not configured correctly or something related to the telegram itself, there is also another project for vapor 3, just a server-db, it has not fallen off for over a year

**Comment by ShaneQi** [comment]
I'd love to help you, I have some questions first:

1. What version ZEGBot are you using?
2. Why do you mention vapor 3? I'm asking because ZEGBot can run without vapor 3.
3. Are you able to get the logs of the non-responsding process?

Thanks!

**Comment by dimabiserov** [comment]
> I'd love to help you, I have some questions first:
> 
> 1. What version ZEGBot are you using?
> 2. How are you using Vapor with ZEGBot? I'm asking because ZEGBot can run without Vapor. Are you mainly running ZEGBot and using some of Vapor's features inside message handling (e.g. when bot receives a particular message, use vapor to do something)?
> 3. Are you able to get the logs of the non-responsding process?
> 
> Thanks!

thank you very much for your reply!
I am using the latest version of your bot and vapor 3, by the way, is it possible to somehow combine your bot and vapor routes work? (server)
I remove "timeout" from self.urlPrefix = "https://api.telegram.org/bot"+token+"/"
and so far everything is fine, if it flies again, I will write here

there are no logs, I do not know how to collect from (

**Comment by ShaneQi** [comment]
Glad to know you found a workaround, hope it works for you long term.

It's not very clear to me what the purpose is to combining vapor routes and ZEGBot.

You can always init a ZEGBot anywhere and use it to send messages, you don't need to call `bot.run` if all you want to do is send something.

e.g.

```
let bot = ZEGBot(token: "TYPE YOUR TOKEN HERE")

do {
  try bot.send(message: "Hello world!", to: AnyChat(chatId: CHAT_ID))
} catch {
  // handle error
}
```

Hope this helps.
